// TODO Implement this library.
library oir_app.globals;

  int actividadSaved   = 0;
  int auxiliarSaved    = 0;
  int transaccionSaved = 0;
  int productoSaved    = 0;
  int cuentaSaved      = 0;
  int cartItemsCounter = 0;
  int registroSaved    = 0;

  String actividadNamed = '';
  String auxiliarNamed  = '';
  String productoNamed  = '';
  String cuentaNamed    = '';
  String tipoSaved      = '';
